//
//  UIColor+UNTAdditions.swift
//
//  Generated by Zeplin on 10/13/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	@nonobjc class var untShadowColor: UIColor { 
		return UIColor(white: 227.0 / 255.0, alpha: 0.38)
	}

	@nonobjc class var untPurpleishBlue: UIColor { 
		return UIColor(red: 61.0 / 255.0, green: 59.0 / 255.0, blue: 238.0 / 255.0, alpha: 0.3)
	}

	@nonobjc class var untPinkishGrey38: UIColor { 
		return UIColor(white: 191.0 / 255.0, alpha: 0.38)
	}

	@nonobjc class var untGreyish: UIColor { 
		return UIColor(white: 166.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var untSelectColor: UIColor { 
		return UIColor(red: 61.0 / 255.0, green: 59.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
	}
}
